Web/Controllers/RealtorController.cs
#nullable disable

using Core.Models;
using Data.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Web.ViewModels;

namespace Web.Controllers
{
    //[Authorize(Roles = "Mäklare")]
    public class RealtorController : Controller
    {
        public static HttpClient Client { get; set; } = new HttpClient();
        private readonly StayContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IEmailSender _emailSender;
        private readonly UserManager<User> _userManager;

        public RealtorController(StayContext context, IWebHostEnvironment webHostEnvironment, UserManager<User> userManager, IEmailSender emailSender)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _userManager = userManager;
            _emailSender = emailSender;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.RealEstateObjects.Include(reo => reo.Images).ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var realEstateObject = await _context.RealEstateObjects
                .FirstOrDefaultAsync(m => m.Id == id);
            if (realEstateObject == null)
            {
                return NotFound();
            }

            return View(realEstateObject);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Address,ZipCode,City,Price,Description,PropType,ContractType,NrOfRooms,LivingArea,GrossArea,PlotSize,ConstructionYear,Balcony,DateForViewing,DateUploaded,Longitude,Latitude")] RealEstateObject realEstateObject, ICollection<IFormFile> inputImages)
        {
            if (realEstateObject.DateUploaded == null)
            {
                realEstateObject.DateUploaded = DateTime.Now;
            }

            string url = $"https://maps.googleapis.com/maps/api/geocode/json?address={realEstateObject.Address},{realEstateObject.City}&key=AIzaSyABG0LJ7DX2Z6R252r4J8Yy0f1aRlyhNFk";
            var coordinatesAsJson = await Client.GetStringAsync(url).ConfigureAwait(false);
            dynamic result = JsonConvert.DeserializeObject<dynamic>(coordinatesAsJson);

            if (result["status"] == "OK")
            {
                IEnumerable<JToken> addressComponents = result["results"][0]["address_components"];
                foreach (JToken addressComponent in addressComponents)
                {
                    foreach (string type in addressComponent["types"])
                    {
                        if (type.Equals("postal_town"))
                        {
                            realEstateObject.PostalTown = addressComponent["long_name"].ToString();
                        }
                        else if (type.Equals("sublocality_level_1"))
                        {
                            realEstateObject.Sublocality = addressComponent["long_name"].ToString();
                        }
                    }
                }
                realEstateObject.Longitude = result["results"][0]["geometry"]["location"]["lng"].Value;
                realEstateObject.Latitude = result["results"][0]["geometry"]["location"]["lat"].Value;
            }

            if (ModelState.IsValid)
            {
                if (inputImages != null)
                {
                    foreach (var image in inputImages)
                    {
                        string fileName = Guid.NewGuid().ToString() + image.FileName;
                        string folder = "images/houses/" + fileName;
                        string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folder);

                        using (var stream = new FileStream(serverFolder, FileMode.Create))
                        {
                            await image.CopyToAsync(stream);
                        }

                        Image imageModel = new Image();
                        imageModel.FileName = fileName;
                        imageModel.RealEstateObject = realEstateObject;

                        realEstateObject.Images.Add(imageModel);
                    }
                }
                var user = await _userManager.GetUserAsync(User);
                realEstateObject.Realtor = user;
                user.UploadedRealEstateObjects.Add(realEstateObject);
                var firm = await _context.RealtorFirms.Where(f => f.Employees.Contains(user)).FirstOrDefaultAsync();
                if (firm != null)
                {
                    firm.FirmListings.Add(realEstateObject);
                }

                _context.Add(realEstateObject);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(realEstateObject);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var realEstateObject = await _context.RealEstateObjects.FindAsync(id);
            if (realEstateObject == null)
            {
                return NotFound();
            }
            return View(realEstateObject);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Address,ZipCode,City,Price,Description,PropType,ContractType,NrOfRooms,LivingArea,GrossArea,PlotSize,ConstructionYear,Balcony,DateForViewing,DateUploaded,Longitude,Latitude")] RealEstateObject realEstateObject)
        {
            if (id != realEstateObject.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(realEstateObject);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RealEstateObjectExists(realEstateObject.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(realEstateObject);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var realEstateObject = await _context.RealEstateObjects
                .FirstOrDefaultAsync(m => m.Id == id);
            if (realEstateObject == null)
            {
                return NotFound();
            }

            return View(realEstateObject);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var realEstateObject = await _context.RealEstateObjects.Include(reo => reo.Images).FirstOrDefaultAsync(reo => reo.Id == id);

            if (realEstateObject != null)
            {
                foreach (var image in realEstateObject.Images)
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\houses", image.FileName);

                    if (System.IO.File.Exists(path))
                    {
                        System.IO.File.Delete(path);
                    }
                }
            }

            _context.RealEstateObjects.Remove(realEstateObject);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RealEstateObjectExists(int id)
        {
            return _context.RealEstateObjects.Any(e => e.Id == id);
        }

        public async Task<IActionResult> CreateVM(RealEstateObjectViewModel model)
        {
            var reo = new RealEstateObject()
            {
                Description = model.DescriptionString,
                PlotSize = Convert.ToDouble(model.PlotSize),
                Balcony = model.Balcony.Equals("1"),
            };

            _context.RealEstateObjects.Add(reo);
            await _context.SaveChangesAsync();

            return View(model);
        }

        public IActionResult InterestedUsers(int id)
        {
            var reo = _context.RealEstateObjects.Include(reo => reo.InterestedUsers).FirstOrDefault(reo => reo.Id == id);

            return View(reo);
        }

        public async Task<IActionResult> NotifyInterestedUsers(int id)
        {
            var reo = _context.RealEstateObjects.Include(reo => reo.InterestedUsers).FirstOrDefault(reo => reo.Id == id);

            var realtorId = _userManager.GetUserId(User);
            var realtor = _context.Users.SingleOrDefault(r => r.Id == realtorId);

            if (reo != null)
            {
                foreach (var user in reo.InterestedUsers)
                {
                    if (user.Email != null)
                    {
                        var defaultMessage = $"<p>Hej {user.FirstName}!</p><br><p>Du får detta meddelande eftersom du har anmält intresse på ett av våra objekt " +
                            $"och nu är det snart dags för visning!</p><p>Den {reo.DateForViewing.ToString("yyyy/MM/dd H:mm")} är du välkommen på visning på {reo.Address}</p><p>" +

Web/Views/Realtor/Details.cshtml
@using Microsoft.AspNetCore.Identity
@using Core.Models
@model RealEstateObject
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

@{
    ViewData["Title"] = $"Detaljer - {Model.Address}";
}

<div class="text-center mt-4">
    <div class="row">
        <div class="btn-group" role="group" aria-label="Selection menu">
            <a class="col-1 btn btn-outline-primary clean-link active" asp-controller="Realtor" asp-action="Details" asp-route-id="@Model.Id"><i class="fa-solid fa-circle-info"></i> Detaljer</a>

            <a class="col-1 btn btn-outline-primary clean-link" asp-controller="Realtor" asp-action="Edit" asp-route-id="@Model.Id"><i class="fa-solid fa-pen-to-square"></i> Redigera</a>

            <a class="col-1 btn btn-outline-primary clean-link" asp-controller="Realtor" asp-action="InterestedUsers" asp-route-id="@Model.Id"><i class="fa-solid fa-clipboard-check"></i> Intresseanmälningar</a>

            <a class="col-1 btn btn-outline-primary clean-link" href="#"><i class="fa-solid fa-message"></i> Meddelandecenter</a>

            <a class="col-1 btn btn-warning clean-link" asp-controller="Realtor" asp-action="Index"><i class="fa-solid fa-angles-left"></i> Tillbaka</a>

        </div>
    </div>
</div>



@{
    ViewData["Title"] = "Privacy Policy";

    var hasBalcony = Model.Balcony ? "Ja" : "Nej";
    var user = await UserManager.GetUserAsync(User);
}

<div class="border border-1 row p-2 my-3 mb-5">
    <div class="row ms-0">
        <h5 class="border border-1 col-4 p-2 mb-0 display-5">
            Realtor goes here
        </h5>
    </div>
    <div class="col-7">
        <div class="border border-1">
            <img src="~/images/resources/your_new_home.jpg" style="height:40vh;width:100%;object-fit:cover;" class="p-2" />
            @*kanske implementera ett bildspel här*@
        </div>
        <div class="mx-1 row">
            <div class="mt-2 col-6" style="font-size:1.1em;">
                <h5 class="mb-0">
                    @Model.Address
                </h5>
            </div>
            <div class="col-6 text-end mt-2">
                <h5 class="mb-0">
                    @Model.Price.ToString("n0") kr
                </h5>
            </div>
            <div>
                @Model.City
            </div>
        </div>
        <div class="border border-1 p-2 my-3">
            @Model.Description
        </div>
    </div>

    <div class="col-4 ms-4">
        <div class="row">
            <div class="col-6">
                Bostadstyp
                <div>
                    <strong>@Model.PropType</strong>
                </div>
            </div>
            <div class="col-6">
                Upplåtelseform
                <div>
                    <strong>@Model.ContractType</strong>
                </div>
            </div>
        </div>
        <div class="row my-4">
            <div class="col-6">
                Antal rum
                <div>
                    <strong>@Model.NrOfRooms rum</strong>
                </div>
            </div>
            <div class="col-6">
                Boarea
                <div>
                    <strong>@Model.LivingArea m²</strong>
                </div>
            </div>
        </div>
        <div class="row my-4">
            <div class="col-6">
                Tomtarea
                <div>
                    <strong>@Model.GrossArea m²</strong>
                </div>
            </div>
            <div class="col-6">
                Byggår
                <div>
                    <strong>@Model.ConstructionYear</strong>
                </div>
            </div>
        </div>
        <div class="row my-4">
            <div class="col-6">
                Balkong
                <div>
                    <strong>@hasBalcony</strong>
                </div>
            </div>
            <div class="col-6">
                Driftkostnad
                <div>
                    <strong>*Not implemented* kr/år</strong>
                </div>
            </div>
        </div>
    </div>
</div>

Web/Views/Realtor/Edit.cshtml
@using Core.Models
@using Microsoft.AspNetCore.Identity
@using Core.Models.Enums

@inject UserManager<User> UserManager

@model RealEstateObject

@{
    ViewData["Title"] = $"Redigera bostadsobjekt - {Model.Address}";
    var realtor = await UserManager.GetUserAsync(User);
}

<style>
    .form-floating {
        margin-bottom: 2%;
    }
</style>

<div class="text-center mt-4">
    <div class="row">
        <div class="btn-group" role="group" aria-label="Selection menu">
            <a class="col-1 btn btn-outline-primary clean-link" asp-controller="Realtor" asp-action="Details" asp-route-id="@Model.Id"><i class="fa-solid fa-circle-info"></i> Detaljer</a>

            <a class="col-1 btn btn-outline-primary clean-link active" asp-controller="Realtor" asp-action="Edit" asp-route-id="@Model.Id"><i class="fa-solid fa-pen-to-square"></i> Redigera</a>

            <a class="col-1 btn btn-outline-primary clean-link" asp-controller="Realtor" asp-action="InterestedUsers" asp-route-id="@Model.Id"><i class="fa-solid fa-clipboard-check"></i> Intresseanmälningar</a>

            <a class="col-1 btn btn-outline-primary clean-link" href="#"><i class="fa-solid fa-message"></i> Meddelandecenter</a>

            <a class="col-1 btn btn-warning clean-link" asp-controller="Realtor" asp-action="Index"><i class="fa-solid fa-angles-left"></i> Tillbaka</a>

        </div>
    </div>
</div>

<form asp-action="Edit" style="margin-top: 5%;">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <div class="border border-1 row p-2 my-3 mb-5" style="border:1px solid #446e9b; box-shadow: rgba(149, 157, 165, 0.2) 0px 8px 24px;">
        <h1 style="margin-top: 1%;">@ViewData["Title"]</h1>
        <hr />
        <div class="row ms-0">
            <h4 style="margin-top: 1%; color:darkgrey;">@realtor.FirstName @realtor.LastName</h4>
            <h5 class="border border-0 col-4 p-2 mb-0 display-5">
                @Model.Address
            </h5>
            <div class="col">
                <div class="float-end row text-end" style="margin-top: -3%;">
                    <div class="display-6 m-0">
                        <a href="#" class="clean-link">
                            <i class="fa-solid fa-star"></i>
                        </a>
                    </div>
                    <div>Spara</div>
                </div>
            </div>
        </div>
        <div class="col-7">
            <div class="border border-1">
                <img src="~/images/resources/your_new_home.jpg" style="height:40vh;width:100%;object-fit:cover;" class="p-2" /> @*kanske implementera ett bildspel här*@
            </div>
            <div class="mx-1 row">
                <div class="mt-2 col-6" style="font-size:1.1em;">
                    <div class="form-floating">
                        <input asp-for="Address" class="form-control" placeholder="Adress" />
                        <label asp-for="Address" class="control-label"></label>
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                    <div class="form-floating">
                        <input asp-for="ZipCode" class="form-control" placeholder="Postnummer" />
                        <label asp-for="ZipCode" class="control-label"></label>
                        <span asp-validation-for="ZipCode" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-6 text-end mt-2">
                    <div class="form-floating">
                        <input asp-for="Price" class="form-control" placeholder="Pris (kr)" />
                        <label asp-for="Price" class="control-label">Pris (kr)</label>
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>
                    <div class="form-floating">
                        <input asp-for="City" class="form-control" placeholder="Stad" />
                        <label asp-for="City" class="control-label"></label>
                        <span asp-validation-for="City" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <br />
            <div class="form-floating mx-1 row mt-2">
                <textarea rows="4" asp-for="Description" class="form-control" placeholder="Beskrivning" style="height: 200%;"></textarea>
                <label asp-for="Description" class="control-label"></label>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
        <div class="col-4 ms-4">
            <div class="row">
                <div class="col-6">
                    <div class="form-floating">
                        <select asp-for="PropType" class="form-control" asp-items="Html.GetEnumSelectList<PropertyType>()">
                            <option>Välj bostadstyp..</option>
                        </select>
                        <label asp-for="PropType" class="control-label"></label>
                        <span asp-validation-for="PropType" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-floating">
                        <select asp-for="ContractType" class="form-control" asp-items="Html.GetEnumSelectList<ContractType>()">
                            <option>Välj upplåtelseform..</option>
                        </select>
                        <label asp-for="ContractType" class="control-label"></label>
                        <span asp-validation-for="ContractType" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row my-4">
                <div class="col-6">
                    <div class="form-floating">
                        <input asp-for="NrOfRooms" class="form-control" placeholder="Antal rum" />
                        <label asp-for="NrOfRooms" class="control-label"></label>
                        <span asp-validation-for="NrOfRooms" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-floating">
                        <input asp-for="LivingArea" class="form-control" placeholder="Boarea" />
                        <label asp-for="LivingArea" class="control-label"></label>
                        <span asp-validation-for="LivingArea" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row my-4">
                <div class="col-6">
                    <div class="form-floating">
                        <input asp-for="PlotSize" class="form-control" placeholder="Tomtarea" />
                        <label asp-for="PlotSize" class="control-label"></label>
                        <span asp-validation-for="PlotSize" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-floating">
                        <input asp-for="ConstructionYear" class="form-control" placeholder="Byggår" />
                        <label asp-for="ConstructionYear" class="control-label"></label>
                        <span asp-validation-for="ConstructionYear" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row my-4">
                <div class="col-6">
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="Balcony" /> @Html.DisplayNameFor(model => model.Balcony)
                        </label>
                    </div>
                </div>
                <div class="col-6">
                    Driftkostnad
                    <div>
                        <strong>*Not implemented* kr/år</strong>
                    </div>
                </div>
            </div>
            <br />
            <div class="mt-2 col-6" style="width: auto;">
                <div class="form-floating" style="margin-top: 4%;">
                    <input asp-for="GrossArea" class="form-control" placeholder="Biarea" />
                    <label asp-for="GrossArea" class="control-label"></label>
                    <span asp-validation-for="GrossArea" class="text-danger"></span>
                </div>
                <div class="form-floating">
                    <input asp-for="DateForViewing" class="form-control" placeholder="Visningsdatum" />
                    <label asp-for="DateForViewing" class="control-label"></label>
                    <span asp-validation-for="DateForViewing" class="text-danger"></span>
                </div>
                <div class="form-floating">
                    <input disabled asp-for="DateUploaded" class="form-control" placeholder="Uppladdningsdatum" />
                    <label asp-for="DateUploaded" class="control-label"></label>
                    <span asp-validation-for="DateUploaded" class="text-danger"></span>
                </div>
                <div class="form-floating">
                    <input asp-for="Images" class="form-control" style="padding-top: 12%; height: auto;" />
                    <label asp-for="Images" class="control-label"></label>
                    <span asp-validation-for="Images" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="form-group" style="margin:2%;">
            <a class="btn btn-primary" asp-action="Index"><i class="fa-solid fa-arrow-left"></i> Tillbaka</a>
            <button type="submit" class="btn btn-success" style="margin-left: 52.5%;"><i class="fa-solid fa-plus"></i> Spara</button>
            <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger" style="margin-left: 15%;"><i class="fa-solid fa-trash-can"></i> Ta bort</a>
        </div>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Web/Views/Realtor/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using Core.Models
@model IEnumerable<RealEstateObject>
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

@{
    ViewData["Title"] = "Mina bostadsobjekt";
    var user = await UserManager.GetUserAsync(User);
}

<div class="text-center mt-4">
    <div class="row">
        <div class="btn-group" role="group" aria-label="Selection menu">
            <a class="col-1 btn btn-outline-primary clean-link" href="#"><i class="fa-solid fa-gauge"></i> Översikt</a>

            <a class="col-1 btn btn-outline-primary clean-link" href="#"><i class="fa-solid fa-briefcase"></i> Mäklarfirma</a>

            <a class="col-1 btn btn-outline-primary clean-link active" asp-controller="Realtor" asp-action="Index"><i class="fa-solid fa-house"></i> Bostadsobjekt</a>
        </div>
    </div>
</div>

<div class="border border-1 row p-2 my-3 mb-5 shadow mb-5">
    <div class="ms-0 row">
        <div class="mt-y my-2">

            <p>
                <a asp-action="Create" class="btn btn-success"><i class="fa-solid fa-plus"></i> Ladda upp bostadsobjekt</a>
            </p>
        </div>
        @if (!user.UploadedRealEstateObjects.Any())
        {
            <div class="card-body">
                Du har ej några upplagda bostäder.
            </div>
        }
        <div>
            @foreach (var item in user.UploadedRealEstateObjects)
            {
                <div class="row ms-0">
                    <div class="card mb-3 col-9 p-0 jockeTransition">
                        <div class="row g-0">
                            <div class="col-4">
                                @*<img src="@item.ImageURL" class="img-fluid rounded-start" style="height:10em;width:100%;object-fit:cover;" />*@
                                @*<img src="~/images/resources/your_new_home.jpg" class="img-fluid rounded-start" style="height:10em;width:100%;object-fit:cover;" alt="picture">*@

                                @if (item.Images.Count > 0)
                                {
                                    <a asp-action="RealEstateObject" asp-route-id="@item.Id" class="clean-link">
                                        @*<img src="@item.ImageURL" class="img-fluid rounded-start" style="height:10em;width:100%;object-fit:cover;" />*@
                                        <img src="~/images/Houses/@item.Images[0].FileName" class="img-fluid rounded-start" style="height:10em;width:100%;object-fit:cover;" alt="picture">
                                    </a>
                                }
                                else
                                {
                                    <a asp-action="RealEstateObject" asp-route-id="@item.Id" class="clean-link">
                                        @*<img src="@item.ImageURL" class="img-fluid rounded-start" style="height:10em;width:100%;object-fit:cover;" />*@
                                        <img src="~/images/resources/your_new_home.jpg" class="img-fluid rounded-start" style="height:10em;width:100%;object-fit:cover;" alt="picture">
                                    </a>
                                }
                            </div>
                            <div class="col-8">
                                <div class="card-body">
                                    <a asp-action="Details" asp-route-id="@item.Id" class="stretched-link clean-link">
                                        <p class="card-text text-truncate col-11"><small class="text-muted">@item.Description</small></p>
                                        <h5 class="card-title mb-0">@item.Address</h5>
                                        <h6 class="card-title">@item.City</h6>
                                        <div class="d-flex justify-content-between pe-4">
                                            <div class="card-text"><strong>@item.Price.ToString("n0") kr</strong></div>
                                            <div class="card-text"><strong>@item.LivingArea.ToString("n0") m²</strong></div>
                                            <div class="card-text"><strong>@item.NrOfRooms rum</strong></div>

                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-3">
                        <a class="col-12 my-1 btn btn-primary" asp-controller="Realtor" asp-action="InterestedUsers" asp-route-id="@item.Id"><i class="fa-solid fa-clipboard-check"></i> Intresseanmälningar</a>
                        <a class="col-12 my-1 btn btn-info" asp-controller="Realtor" asp-action="Edit" asp-route-id="@item.Id"><i class="fa-solid fa-pen-to-square"></i> Redigera</a>
                        <a class="col-12 my-1 btn btn-warning" href="#"><i class="fa-solid fa-message"></i> Meddelandecenter</a>
                    </div>
                </div>

            }
        </div>
    </div>
</div>

Web/Views/Realtor/InterestedUsers.cshtml
@using Core.Models
@model RealEstateObject
@{
    ViewData["Title"] = $"Intresseanmälningar - {Model.Address}";

    var user = new User();
}

<div class="text-center mt-4">
    <div class="row">
        <div class="btn-group" role="group" aria-label="Selection menu">
            <a class="col-1 btn btn-outline-primary clean-link" asp-controller="Realtor" asp-action="Details" asp-route-id="@Model.Id"><i class="fa-solid fa-circle-info"></i> Detaljer</a>

            <a class="col-1 btn btn-outline-primary clean-link" asp-controller="Realtor" asp-action="Edit" asp-route-id="@Model.Id"><i class="fa-solid fa-pen-to-square"></i> Redigera</a>

            <a class="col-1 btn btn-outline-primary clean-link active" asp-controller="Realtor" asp-action="InterestedUsers" asp-route-id="@Model.Id"><i class="fa-solid fa-clipboard-check"></i> Intresseanmälningar</a>

            <a class="col-1 btn btn-outline-primary clean-link" href="#"><i class="fa-solid fa-message"></i> Meddelandecenter</a>

            <a class="col-1 btn btn-warning clean-link" asp-controller="Realtor" asp-action="Index"><i class="fa-solid fa-angles-left"></i> Tillbaka</a>

        </div>
    </div>
</div>

@if (Model.InterestedUsers.Any())
{
    <div class="mt-4 mb-2 text-end">
        <a class="btn btn-info" asp-action="NotifyInterestedUsers" asp-route-id="@Model.Id"><i class="fa-solid fa-paper-plane"></i> Meddela om visning</a>
    </div>

    <table class="table table-hover">
        <thead>
            <tr>
                <th class="col-3">Namn</th>
                <th class="col-3">Adress</th>
                <th class="col-3">Telefonnummer</th>
                <th class="col-3">Epost</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.InterestedUsers)
            {
                <tr>
                    <td>@item.FirstName @item.LastName</td>
                    <td>@item.Address, @item.ZipCode, @item.City</td>
                    <td>@item.PhoneNumber</td>
                    <td>@item.Email</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h4 class="mt-4">Ingen har anmält intresse på detta objekt än</h4>
}